version: "3.8"

services:
  db:
    image: postgres:15
    container_name: next-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: nextdb
    volumes:
      - next-postgres-data:/var/lib/postgresql/data

volumes:
  next-postgres-data:
